// Region assignment for every country name key used in
// components/InteractiveMap.tsx's COUNTRY_COORDS, grouped the same way as
// that file's own comment sections (Americas split into North America vs.
// Latin America & Caribbean; Middle East carved out of Africa/Asia to match
// the COUNTRY_COORDS "// Middle East" block, incl. Turkey/Afghanistan/Egypt).
export const COUNTRY_REGIONS: Record<string, string> = {
  // North America
  Canada: "North America",

  // Latin America & Caribbean
  Mexico: "Latin America & Caribbean",
  Brazil: "Latin America & Caribbean",
  Colombia: "Latin America & Caribbean",
  Venezuela: "Latin America & Caribbean",
  Peru: "Latin America & Caribbean",
  Argentina: "Latin America & Caribbean",
  Ecuador: "Latin America & Caribbean",
  Chile: "Latin America & Caribbean",
  Bolivia: "Latin America & Caribbean",
  Paraguay: "Latin America & Caribbean",
  Uruguay: "Latin America & Caribbean",
  Guyana: "Latin America & Caribbean",
  Suriname: "Latin America & Caribbean",
  "Trinidad and Tobago": "Latin America & Caribbean",
  Trinidad: "Latin America & Caribbean",
  Jamaica: "Latin America & Caribbean",
  Cuba: "Latin America & Caribbean",
  Haiti: "Latin America & Caribbean",
  "Dominican Republic": "Latin America & Caribbean",
  "Puerto Rico": "Latin America & Caribbean",
  Guatemala: "Latin America & Caribbean",
  "El Salvador": "Latin America & Caribbean",
  Honduras: "Latin America & Caribbean",
  Nicaragua: "Latin America & Caribbean",
  "Costa Rica": "Latin America & Caribbean",
  Panama: "Latin America & Caribbean",
  Belize: "Latin America & Caribbean",
  Barbados: "Latin America & Caribbean",
  Bahamas: "Latin America & Caribbean",
  "Antigua and Barbuda": "Latin America & Caribbean",
  Grenada: "Latin America & Caribbean",
  "Saint Lucia": "Latin America & Caribbean",
  Guadeloupe: "Latin America & Caribbean",
  Martinique: "Latin America & Caribbean",

  // Europe
  "United Kingdom": "Europe",
  UK: "Europe",
  England: "Europe",
  Scotland: "Europe",
  Wales: "Europe",
  Ireland: "Europe",
  France: "Europe",
  Germany: "Europe",
  Italy: "Europe",
  Spain: "Europe",
  Portugal: "Europe",
  Netherlands: "Europe",
  Belgium: "Europe",
  Switzerland: "Europe",
  Austria: "Europe",
  Sweden: "Europe",
  Norway: "Europe",
  Denmark: "Europe",
  Finland: "Europe",
  Poland: "Europe",
  Ukraine: "Europe",
  Russia: "Europe",
  Romania: "Europe",
  Hungary: "Europe",
  "Czech Republic": "Europe",
  Czechia: "Europe",
  Slovakia: "Europe",
  Bulgaria: "Europe",
  Serbia: "Europe",
  Croatia: "Europe",
  "Bosnia and Herzegovina": "Europe",
  Bosnia: "Europe",
  Albania: "Europe",
  Greece: "Europe",
  Turkey: "Europe",
  Lithuania: "Europe",
  Latvia: "Europe",
  Estonia: "Europe",
  Belarus: "Europe",
  Moldova: "Europe",
  "North Macedonia": "Europe",
  Kosovo: "Europe",
  Montenegro: "Europe",
  Slovenia: "Europe",
  Luxembourg: "Europe",
  Iceland: "Europe",
  Malta: "Europe",
  Cyprus: "Europe",

  // Middle East
  Iran: "Middle East",
  Iraq: "Middle East",
  Syria: "Middle East",
  Lebanon: "Middle East",
  Israel: "Middle East",
  Jordan: "Middle East",
  "Saudi Arabia": "Middle East",
  Yemen: "Middle East",
  Kuwait: "Middle East",
  UAE: "Middle East",
  "United Arab Emirates": "Middle East",
  Qatar: "Middle East",
  Bahrain: "Middle East",
  Oman: "Middle East",
  Palestine: "Middle East",
  Afghanistan: "Middle East",
  Egypt: "Middle East",
  Libya: "Middle East",
  Tunisia: "Middle East",
  Algeria: "Middle East",
  Morocco: "Middle East",

  // Asia
  China: "Asia",
  India: "Asia",
  Pakistan: "Asia",
  Bangladesh: "Asia",
  "Sri Lanka": "Asia",
  Nepal: "Asia",
  Bhutan: "Asia",
  Japan: "Asia",
  "South Korea": "Asia",
  Korea: "Asia",
  "North Korea": "Asia",
  Taiwan: "Asia",
  "Hong Kong": "Asia",
  Vietnam: "Asia",
  Thailand: "Asia",
  Indonesia: "Asia",
  Malaysia: "Asia",
  Philippines: "Asia",
  Myanmar: "Asia",
  Burma: "Asia",
  Cambodia: "Asia",
  Laos: "Asia",
  Singapore: "Asia",
  Mongolia: "Asia",
  Kazakhstan: "Asia",
  Uzbekistan: "Asia",
  Kyrgyzstan: "Asia",
  Tajikistan: "Asia",
  Turkmenistan: "Asia",
  Azerbaijan: "Asia",
  Georgia: "Asia",
  Armenia: "Asia",

  // Africa
  Nigeria: "Africa",
  Ethiopia: "Africa",
  Kenya: "Africa",
  Ghana: "Africa",
  "South Africa": "Africa",
  Tanzania: "Africa",
  Uganda: "Africa",
  Cameroon: "Africa",
  Somalia: "Africa",
  Sudan: "Africa",
  "South Sudan": "Africa",
  Eritrea: "Africa",
  Rwanda: "Africa",
  Zimbabwe: "Africa",
  Zambia: "Africa",
  Senegal: "Africa",
  Liberia: "Africa",
  "Sierra Leone": "Africa",
  Guinea: "Africa",
  "Ivory Coast": "Africa",
  "Côte d'Ivoire": "Africa",
  Congo: "Africa",
  "Democratic Republic of the Congo": "Africa",
  DRC: "Africa",
  Angola: "Africa",
  Mozambique: "Africa",
  Madagascar: "Africa",
  Malawi: "Africa",
  Botswana: "Africa",
  Namibia: "Africa",
  Gabon: "Africa",
  Burundi: "Africa",
  Mali: "Africa",
  Niger: "Africa",
  Chad: "Africa",
  "Burkina Faso": "Africa",
  Togo: "Africa",
  Benin: "Africa",
  Mauritania: "Africa",
  "Cape Verde": "Africa",

  // Oceania
  Australia: "Oceania",
  "New Zealand": "Oceania",
  Fiji: "Oceania",
  "Papua New Guinea": "Oceania",
};

// Fuzzy region lookup mirroring InteractiveMap's lookupCountry() matching
// order (exact, case-insensitive exact, then substring) so freeform
// country_of_origin text degrades gracefully instead of throwing away tier 2.
export function lookupRegion(name: string | null | undefined): string | null {
  if (!name) return null;
  const n = name.trim();
  if (!n) return null;
  if (COUNTRY_REGIONS[n]) return COUNTRY_REGIONS[n];
  const lower = n.toLowerCase();
  for (const [key, region] of Object.entries(COUNTRY_REGIONS)) {
    if (key.toLowerCase() === lower) return region;
  }
  for (const [key, region] of Object.entries(COUNTRY_REGIONS)) {
    const kl = key.toLowerCase();
    if (lower.includes(kl) || kl.includes(lower)) return region;
  }
  return null;
}
