export const TOTAL_QUESTIONS = 8;

export type UIStrings = {
  placeholder: string;
  placeholderRecording: string;
  placeholderWaiting: string;
  clickToTalk: string;
  recordingLabel: string;
  clickToStop: string;
  continueBtn: string;
  replay: string;
  stop: string;
  startOver: string;
  progressText: (n: number) => string;
  progressLost: string;
  yesReset: string;
  cancelConfirm: string;
  recordingStatus: string;
  processingRecording: string;
  noSpeechDetected: string;
  noSoundLive: string;
  transcriptHint: string;
  preferNotToSay: string;
  mapNudge: string;
  ageGateTitle: string;
  ageGateBody: string;
  ageGateMonth: string;
  ageGateDay: string;
  ageGateYear: string;
  ageGateConfirm: string;
  ageGateContinue: string;
  ageGateSubmitting: string;
  ageGateError: string;
  ageGateBlockedTitle: string;
  ageGateBlockedBody: string;
};

export const UI_STRINGS: Record<string, UIStrings> = {
  en: {
    placeholder: "Share your answer… (Enter to send, Shift+Enter for new line)",
    placeholderRecording: "Recording… click ⏹ to stop",
    placeholderWaiting: "Waiting for response…",
    clickToTalk: "Click to Talk",
    recordingLabel: "Recording…",
    clickToStop: "Click to Stop",
    continueBtn: "Continue",
    replay: "Replay",
    stop: "Stop",
    startOver: "Start Over",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} questions`,
    progressLost: "Progress will be lost.",
    yesReset: "Yes, reset",
    cancelConfirm: "Cancel",
    recordingStatus: "Recording…",
    processingRecording: "Processing recording…",
    noSpeechDetected: "We couldn't hear that clearly. Try recording again, or type your answer.",
    noSoundLive: "We're not hearing any sound. Check your microphone, or stop and type your answer instead.",
    transcriptHint: "Tap the text above to make changes, or press Continue.",
    preferNotToSay: "Prefer not to say",
    mapNudge: "Choosing a state adds your journey to the Journey Map.",
    ageGateTitle: "Before You Share",
    ageGateBody: "To help keep our community safe, please confirm your date of birth before sharing your story.",
    ageGateMonth: "Month",
    ageGateDay: "Day",
    ageGateYear: "Year",
    ageGateConfirm: "By continuing you confirm this information is accurate.",
    ageGateContinue: "Continue",
    ageGateSubmitting: "Checking…",
    ageGateError: "Please select a valid date of birth.",
    ageGateBlockedTitle: "Thanks for letting us know",
    ageGateBlockedBody: "You must be 13 or older to share a story here. We hope you'll come back and share when you're a bit older!",
  },
  es: {
    placeholder: "Comparte tu respuesta… (Intro para enviar, Shift+Intro para nueva línea)",
    placeholderRecording: "Grabando… haz clic en ⏹ para parar",
    placeholderWaiting: "Esperando respuesta…",
    clickToTalk: "Clic para hablar",
    recordingLabel: "Grabando…",
    clickToStop: "Clic para parar",
    continueBtn: "Continuar",
    replay: "Reproducir",
    stop: "Detener",
    startOver: "Empezar de nuevo",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} preguntas`,
    progressLost: "Se perderá el progreso.",
    yesReset: "Sí, reiniciar",
    cancelConfirm: "Cancelar",
    recordingStatus: "Grabando…",
    processingRecording: "Procesando grabación…",
    noSpeechDetected: "No pudimos escucharte bien. Intenta grabar de nuevo o escribe tu respuesta.",
    noSoundLive: "No estamos escuchando ningún sonido. Comprueba tu micrófono o para y escribe tu respuesta.",
    transcriptHint: "Toca el texto de arriba para hacer cambios, o presiona Continuar.",
    preferNotToSay: "Prefiero no decirlo",
    mapNudge: "Elegir un estado añade tu viaje al Mapa del Viaje.",
    ageGateTitle: "Antes de compartir",
    ageGateBody: "Para ayudar a mantener segura nuestra comunidad, confirma tu fecha de nacimiento antes de compartir tu historia.",
    ageGateMonth: "Mes",
    ageGateDay: "Día",
    ageGateYear: "Año",
    ageGateConfirm: "Al continuar, confirmas que esta información es correcta.",
    ageGateContinue: "Continuar",
    ageGateSubmitting: "Comprobando…",
    ageGateError: "Selecciona una fecha de nacimiento válida.",
    ageGateBlockedTitle: "Gracias por decírnoslo",
    ageGateBlockedBody: "Debes tener 13 años o más para compartir una historia aquí. ¡Esperamos que vuelvas a compartir cuando seas un poco mayor!",
  },
  fr: {
    placeholder: "Partagez votre réponse… (Entrée pour envoyer, Maj+Entrée pour nouvelle ligne)",
    placeholderRecording: "Enregistrement… cliquez sur ⏹ pour arrêter",
    placeholderWaiting: "En attente de réponse…",
    clickToTalk: "Cliquez pour parler",
    recordingLabel: "Enregistrement…",
    clickToStop: "Clic pour arrêter",
    continueBtn: "Continuer",
    replay: "Rejouer",
    stop: "Arrêter",
    startOver: "Recommencer",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} questions`,
    progressLost: "La progression sera perdue.",
    yesReset: "Oui, réinitialiser",
    cancelConfirm: "Annuler",
    recordingStatus: "Enregistrement…",
    processingRecording: "Traitement de l'enregistrement…",
    noSpeechDetected: "Nous n'avons pas pu vous entendre clairement. Réessayez d'enregistrer ou tapez votre réponse.",
    noSoundLive: "Nous n'entendons aucun son. Vérifiez votre microphone, ou arrêtez et tapez votre réponse.",
    transcriptHint: "Touchez le texte ci-dessus pour apporter des modifications, ou appuyez sur Continuer.",
    preferNotToSay: "Je préfère ne pas préciser",
    mapNudge: "Choisir un état ajoute votre parcours à la Carte du Voyage.",
    ageGateTitle: "Avant de partager",
    ageGateBody: "Pour aider à assurer la sécurité de notre communauté, veuillez confirmer votre date de naissance avant de partager votre histoire.",
    ageGateMonth: "Mois",
    ageGateDay: "Jour",
    ageGateYear: "Année",
    ageGateConfirm: "En continuant, vous confirmez que ces informations sont exactes.",
    ageGateContinue: "Continuer",
    ageGateSubmitting: "Vérification…",
    ageGateError: "Veuillez sélectionner une date de naissance valide.",
    ageGateBlockedTitle: "Merci de nous l'avoir dit",
    ageGateBlockedBody: "Vous devez avoir au moins 13 ans pour partager une histoire ici. Nous espérons que vous reviendrez partager votre histoire un peu plus tard !",
  },
  pt: {
    placeholder: "Compartilhe sua resposta… (Enter para enviar, Shift+Enter para nova linha)",
    placeholderRecording: "Gravando… clique em ⏹ para parar",
    placeholderWaiting: "Aguardando resposta…",
    clickToTalk: "Clique para falar",
    recordingLabel: "Gravando…",
    clickToStop: "Clique para parar",
    continueBtn: "Continuar",
    replay: "Reproduzir",
    stop: "Parar",
    startOver: "Recomeçar",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} perguntas`,
    progressLost: "O progresso será perdido.",
    yesReset: "Sim, reiniciar",
    cancelConfirm: "Cancelar",
    recordingStatus: "Gravando…",
    processingRecording: "Processando gravação…",
    noSpeechDetected: "Não conseguimos ouvi-lo bem. Tente gravar novamente ou escreva sua resposta.",
    noSoundLive: "Não estamos ouvindo nenhum som. Verifique seu microfone ou pare e escreva sua resposta.",
    transcriptHint: "Toque no texto acima para fazer alterações, ou pressione Continuar.",
    preferNotToSay: "Prefiro não dizer",
    mapNudge: "Escolher um estado adiciona sua jornada ao Mapa da Jornada.",
    ageGateTitle: "Antes de compartilhar",
    ageGateBody: "Para ajudar a manter nossa comunidade segura, confirme sua data de nascimento antes de compartilhar sua história.",
    ageGateMonth: "Mês",
    ageGateDay: "Dia",
    ageGateYear: "Ano",
    ageGateConfirm: "Ao continuar, você confirma que esta informação é precisa.",
    ageGateContinue: "Continuar",
    ageGateSubmitting: "Verificando…",
    ageGateError: "Selecione uma data de nascimento válida.",
    ageGateBlockedTitle: "Obrigado por nos avisar",
    ageGateBlockedBody: "Você precisa ter 13 anos ou mais para compartilhar uma história aqui. Esperamos que volte para compartilhar quando for um pouco mais velho!",
  },
  de: {
    placeholder: "Teile deine Antwort… (Eingabe zum Senden, Umschalt+Eingabe für neue Zeile)",
    placeholderRecording: "Aufnahme… klicke ⏹ zum Stoppen",
    placeholderWaiting: "Warte auf Antwort…",
    clickToTalk: "Klicken zum Reden",
    recordingLabel: "Aufnahme…",
    clickToStop: "Klicken stoppen",
    continueBtn: "Weiter",
    replay: "Wiederholen",
    stop: "Stoppen",
    startOver: "Neu starten",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} Fragen`,
    progressLost: "Fortschritt geht verloren.",
    yesReset: "Ja, zurücksetzen",
    cancelConfirm: "Abbrechen",
    recordingStatus: "Aufnahme…",
    processingRecording: "Aufnahme wird verarbeitet…",
    noSpeechDetected: "Wir konnten das nicht klar hören. Versuche es erneut aufzunehmen oder tippe deine Antwort.",
    noSoundLive: "Wir hören keinen Ton. Überprüfe dein Mikrofon, oder stoppe die Aufnahme und tippe deine Antwort.",
    transcriptHint: "Tippe auf den Text oben, um Änderungen vorzunehmen, oder drücke Weiter.",
    preferNotToSay: "Keine Angabe",
    mapNudge: "Die Auswahl eines Bundesstaats fügt deine Reise der Reisekarte hinzu.",
    ageGateTitle: "Bevor du teilst",
    ageGateBody: "Um unsere Community sicher zu halten, bestätige bitte dein Geburtsdatum, bevor du deine Geschichte teilst.",
    ageGateMonth: "Monat",
    ageGateDay: "Tag",
    ageGateYear: "Jahr",
    ageGateConfirm: "Mit dem Fortfahren bestätigst du, dass diese Angaben korrekt sind.",
    ageGateContinue: "Weiter",
    ageGateSubmitting: "Wird geprüft…",
    ageGateError: "Bitte wähle ein gültiges Geburtsdatum.",
    ageGateBlockedTitle: "Danke, dass du es uns mitgeteilt hast",
    ageGateBlockedBody: "Du musst mindestens 13 Jahre alt sein, um hier eine Geschichte zu teilen. Wir hoffen, du kommst zurück, wenn du etwas älter bist!",
  },
  it: {
    placeholder: "Condividi la tua risposta… (Invio per inviare, Maiusc+Invio per nuova riga)",
    placeholderRecording: "Registrazione… clicca ⏹ per fermare",
    placeholderWaiting: "In attesa di risposta…",
    clickToTalk: "Clicca per parlare",
    recordingLabel: "Registrazione…",
    clickToStop: "Clicca per fermare",
    continueBtn: "Continua",
    replay: "Riproduci",
    stop: "Ferma",
    startOver: "Ricomincia",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} domande`,
    progressLost: "Il progresso verrà perso.",
    yesReset: "Sì, ripristina",
    cancelConfirm: "Annulla",
    recordingStatus: "Registrazione…",
    processingRecording: "Elaborazione registrazione…",
    noSpeechDetected: "Non siamo riusciti a sentirti bene. Riprova a registrare o digita la tua risposta.",
    noSoundLive: "Non stiamo sentendo nessun suono. Controlla il microfono, oppure fermati e digita la tua risposta.",
    transcriptHint: "Tocca il testo sopra per apportare modifiche, oppure premi Continua.",
    preferNotToSay: "Preferisco non dirlo",
    mapNudge: "Scegliere uno stato aggiunge il tuo viaggio alla Mappa del Viaggio.",
    ageGateTitle: "Prima di condividere",
    ageGateBody: "Per aiutare a mantenere sicura la nostra community, conferma la tua data di nascita prima di condividere la tua storia.",
    ageGateMonth: "Mese",
    ageGateDay: "Giorno",
    ageGateYear: "Anno",
    ageGateConfirm: "Continuando, confermi che questi dati sono corretti.",
    ageGateContinue: "Continua",
    ageGateSubmitting: "Verifica in corso…",
    ageGateError: "Seleziona una data di nascita valida.",
    ageGateBlockedTitle: "Grazie per avercelo detto",
    ageGateBlockedBody: "Devi avere almeno 13 anni per condividere una storia qui. Speriamo che tu torni a condividere quando sarai un po' più grande!",
  },
  zh: {
    placeholder: "分享您的回答…（Enter 发送，Shift+Enter 换行）",
    placeholderRecording: "录音中… 点击 ⏹ 停止",
    placeholderWaiting: "等待回应中…",
    clickToTalk: "点击说话",
    recordingLabel: "录音中…",
    clickToStop: "点击停止",
    continueBtn: "继续",
    replay: "重放",
    stop: "停止",
    startOver: "重新开始",
    progressText: (n) => `第 ${n}/${TOTAL_QUESTIONS} 题`,
    progressLost: "进度将会丢失。",
    yesReset: "是，重置",
    cancelConfirm: "取消",
    recordingStatus: "录音中…",
    processingRecording: "处理录音中…",
    noSpeechDetected: "我们听不清楚。请重新录音，或直接输入您的回答。",
    noSoundLive: "我们没有听到任何声音。请检查您的麦克风，或停止录音并输入您的回答。",
    transcriptHint: "点按上方文字进行修改，或点击继续。",
    preferNotToSay: "不愿透露",
    mapNudge: "选择一个州会将您的旅程添加到旅程地图上。",
    ageGateTitle: "分享前",
    ageGateBody: "为了帮助保障社区安全，请在分享您的故事前确认您的出生日期。",
    ageGateMonth: "月",
    ageGateDay: "日",
    ageGateYear: "年",
    ageGateConfirm: "继续即表示您确认此信息准确无误。",
    ageGateContinue: "继续",
    ageGateSubmitting: "正在检查…",
    ageGateError: "请选择有效的出生日期。",
    ageGateBlockedTitle: "感谢您的告知",
    ageGateBlockedBody: "您必须年满13岁才能在此分享故事。希望您年长一些后再回来分享！",
  },
  ja: {
    placeholder: "回答を入力してください…（Enterで送信、Shift+Enterで改行）",
    placeholderRecording: "録音中… ⏹ をクリックして停止",
    placeholderWaiting: "応答を待っています…",
    clickToTalk: "クリックして話す",
    recordingLabel: "録音中…",
    clickToStop: "クリックして停止",
    continueBtn: "続ける",
    replay: "再生",
    stop: "停止",
    startOver: "最初からやり直す",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} 問`,
    progressLost: "進捗が失われます。",
    yesReset: "はい、リセット",
    cancelConfirm: "キャンセル",
    recordingStatus: "録音中…",
    processingRecording: "録音を処理中…",
    noSpeechDetected: "はっきりと聞き取れませんでした。もう一度録音するか、回答を入力してください。",
    noSoundLive: "音が聞こえません。マイクを確認するか、停止して回答を入力してください。",
    transcriptHint: "上のテキストをタップして変更するか、続けるを押してください。",
    preferNotToSay: "回答しない",
    mapNudge: "州を選択すると、あなたの旅がジャーニーマップに追加されます。",
    ageGateTitle: "共有する前に",
    ageGateBody: "コミュニティの安全を守るため、ストーリーを共有する前に生年月日をご確認ください。",
    ageGateMonth: "月",
    ageGateDay: "日",
    ageGateYear: "年",
    ageGateConfirm: "続行することで、この情報が正確であることを確認したものとします。",
    ageGateContinue: "続ける",
    ageGateSubmitting: "確認中…",
    ageGateError: "有効な生年月日を選択してください。",
    ageGateBlockedTitle: "教えてくれてありがとうございます",
    ageGateBlockedBody: "ここでストーリーを共有するには13歳以上である必要があります。もう少し大きくなったら、またぜひ共有しに来てください！",
  },
  ko: {
    placeholder: "답변을 입력하세요…（Enter로 전송, Shift+Enter로 줄바꿈）",
    placeholderRecording: "녹음 중… ⏹ 클릭하여 중지",
    placeholderWaiting: "응답 기다리는 중…",
    clickToTalk: "클릭하여 말하기",
    recordingLabel: "녹음 중…",
    clickToStop: "클릭하여 중지",
    continueBtn: "계속",
    replay: "다시 듣기",
    stop: "정지",
    startOver: "처음부터 다시",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} 질문`,
    progressLost: "진행 상황이 사라집니다.",
    yesReset: "예, 초기화",
    cancelConfirm: "취소",
    recordingStatus: "녹음 중…",
    processingRecording: "녹음 처리 중…",
    noSpeechDetected: "명확하게 들리지 않았습니다. 다시 녹음하거나 답변을 입력해 주세요.",
    noSoundLive: "소리가 들리지 않아요. 마이크를 확인하거나, 중지하고 답변을 입력해 주세요.",
    transcriptHint: "위 텍스트를 탭하여 수정하거나 계속을 누르세요.",
    preferNotToSay: "밝히지 않음",
    mapNudge: "주를 선택하면 여정이 여정 지도에 추가됩니다.",
    ageGateTitle: "공유하기 전에",
    ageGateBody: "커뮤니티의 안전을 위해 이야기를 공유하기 전에 생년월일을 확인해 주세요.",
    ageGateMonth: "월",
    ageGateDay: "일",
    ageGateYear: "년",
    ageGateConfirm: "계속 진행하면 이 정보가 정확함을 확인하는 것입니다.",
    ageGateContinue: "계속",
    ageGateSubmitting: "확인 중…",
    ageGateError: "유효한 생년월일을 선택해 주세요.",
    ageGateBlockedTitle: "알려주셔서 감사합니다",
    ageGateBlockedBody: "여기에서 이야기를 공유하려면 13세 이상이어야 합니다. 조금 더 자란 후에 다시 와서 공유해 주시길 바랍니다!",
  },
  ar: {
    placeholder: "شارك إجابتك… (Enter للإرسال، Shift+Enter لسطر جديد)",
    placeholderRecording: "جارٍ التسجيل… انقر على ⏹ للتوقف",
    placeholderWaiting: "في انتظار الرد…",
    clickToTalk: "انقر للتحدث",
    recordingLabel: "تسجيل…",
    clickToStop: "انقر للإيقاف",
    continueBtn: "متابعة",
    replay: "إعادة",
    stop: "إيقاف",
    startOver: "البدء من جديد",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} أسئلة`,
    progressLost: "سيُفقد التقدم.",
    yesReset: "نعم، إعادة ضبط",
    cancelConfirm: "إلغاء",
    recordingStatus: "تسجيل…",
    processingRecording: "معالجة التسجيل…",
    noSpeechDetected: "لم نتمكن من سماعك بوضوح. حاول التسجيل مرة أخرى أو اكتب إجابتك.",
    noSoundLive: "لا نسمع أي صوت. تحقق من الميكروفون، أو أوقف التسجيل واكتب إجابتك.",
    transcriptHint: "اضغط على النص أعلاه لإجراء تغييرات، أو اضغط على متابعة.",
    preferNotToSay: "أفضل عدم الإفصاح",
    mapNudge: "اختيار ولاية يضيف رحلتك إلى خريطة الرحلة.",
    ageGateTitle: "قبل المشاركة",
    ageGateBody: "للمساعدة في الحفاظ على أمان مجتمعنا، يُرجى تأكيد تاريخ ميلادك قبل مشاركة قصتك.",
    ageGateMonth: "الشهر",
    ageGateDay: "اليوم",
    ageGateYear: "السنة",
    ageGateConfirm: "بالمتابعة، فإنك تؤكد أن هذه المعلومات دقيقة.",
    ageGateContinue: "متابعة",
    ageGateSubmitting: "جارٍ التحقق…",
    ageGateError: "يرجى اختيار تاريخ ميلاد صحيح.",
    ageGateBlockedTitle: "شكرًا لإخبارنا",
    ageGateBlockedBody: "يجب أن يكون عمرك 13 عامًا أو أكثر لمشاركة قصة هنا. نأمل أن تعود لمشاركة قصتك عندما تكبر قليلاً!",
  },
  hi: {
    placeholder: "अपना उत्तर साझा करें… (भेजने के लिए Enter, नई पंक्ति के लिए Shift+Enter)",
    placeholderRecording: "रिकॉर्डिंग… रोकने के लिए ⏹ क्लिक करें",
    placeholderWaiting: "प्रतिक्रिया की प्रतीक्षा…",
    clickToTalk: "बात करने के लिए क्लिक करें",
    recordingLabel: "रिकॉर्डिंग…",
    clickToStop: "रोकने के लिए क्लिक करें",
    continueBtn: "जारी रखें",
    replay: "दोबारा सुनें",
    stop: "रोकें",
    startOver: "फिर से शुरू करें",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} प्रश्न`,
    progressLost: "प्रगति खो जाएगी।",
    yesReset: "हाँ, रीसेट करें",
    cancelConfirm: "रद्द करें",
    recordingStatus: "रिकॉर्डिंग…",
    processingRecording: "रिकॉर्डिंग प्रोसेस हो रही है…",
    noSpeechDetected: "हम आपको स्पष्ट रूप से नहीं सुन सके। दोबारा रिकॉर्ड करें या अपना उत्तर टाइप करें।",
    noSoundLive: "हमें कोई आवाज़ नहीं सुनाई दे रही। अपना माइक्रोफ़ोन जाँचें, या रोकें और अपना उत्तर टाइप करें।",
    transcriptHint: "बदलाव करने के लिए ऊपर दिए गए टेक्स्ट पर टैप करें, या जारी रखें दबाएँ।",
    preferNotToSay: "बताना नहीं चाहते",
    mapNudge: "राज्य चुनने से आपकी यात्रा जर्नी मैप में जुड़ जाती है।",
    ageGateTitle: "साझा करने से पहले",
    ageGateBody: "हमारे समुदाय को सुरक्षित रखने में मदद के लिए, कृपया अपनी कहानी साझा करने से पहले अपनी जन्मतिथि की पुष्टि करें।",
    ageGateMonth: "महीना",
    ageGateDay: "दिन",
    ageGateYear: "वर्ष",
    ageGateConfirm: "जारी रखकर, आप पुष्टि करते हैं कि यह जानकारी सही है।",
    ageGateContinue: "जारी रखें",
    ageGateSubmitting: "जाँच हो रही है…",
    ageGateError: "कृपया एक मान्य जन्मतिथि चुनें।",
    ageGateBlockedTitle: "हमें बताने के लिए धन्यवाद",
    ageGateBlockedBody: "यहाँ कहानी साझा करने के लिए आपकी उम्र 13 वर्ष या उससे अधिक होनी चाहिए। हमें उम्मीद है कि आप थोड़े बड़े होने पर वापस आकर साझा करेंगे!",
  },
  ru: {
    placeholder: "Поделитесь своим ответом… (Enter — отправить, Shift+Enter — новая строка)",
    placeholderRecording: "Запись… нажмите ⏹ для остановки",
    placeholderWaiting: "Ожидание ответа…",
    clickToTalk: "Нажмите говорить",
    recordingLabel: "Запись…",
    clickToStop: "Нажмите стоп",
    continueBtn: "Продолжить",
    replay: "Повтор",
    stop: "Стоп",
    startOver: "Начать заново",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} вопросов`,
    progressLost: "Прогресс будет потерян.",
    yesReset: "Да, сбросить",
    cancelConfirm: "Отмена",
    recordingStatus: "Запись…",
    processingRecording: "Обработка записи…",
    noSpeechDetected: "Нам не удалось чётко расслышать. Попробуйте записать снова или напечатайте ответ.",
    noSoundLive: "Мы не слышим звука. Проверьте микрофон или остановите запись и напечатайте ответ.",
    transcriptHint: "Нажмите на текст выше, чтобы внести изменения, или нажмите «Продолжить».",
    preferNotToSay: "Предпочитаю не указывать",
    mapNudge: "Выбор штата добавляет ваше путешествие на Карту путешествий.",
    ageGateTitle: "Прежде чем поделиться",
    ageGateBody: "Чтобы наше сообщество оставалось безопасным, подтвердите, пожалуйста, дату рождения перед публикацией своей истории.",
    ageGateMonth: "Месяц",
    ageGateDay: "День",
    ageGateYear: "Год",
    ageGateConfirm: "Продолжая, вы подтверждаете точность этих данных.",
    ageGateContinue: "Продолжить",
    ageGateSubmitting: "Проверка…",
    ageGateError: "Пожалуйста, выберите корректную дату рождения.",
    ageGateBlockedTitle: "Спасибо, что сообщили нам",
    ageGateBlockedBody: "Чтобы делиться историей здесь, вам должно быть не менее 13 лет. Надеемся, вы вернётесь, когда станете немного старше!",
  },
  uk: {
    placeholder: "Поділіться своєю відповіддю… (Enter — надіслати, Shift+Enter — новий рядок)",
    placeholderRecording: "Запис… натисніть ⏹ для зупинки",
    placeholderWaiting: "Очікування відповіді…",
    clickToTalk: "Натисніть говорити",
    recordingLabel: "Запис…",
    clickToStop: "Натисніть зупинити",
    continueBtn: "Продовжити",
    replay: "Повтор",
    stop: "Зупинити",
    startOver: "Почати знову",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} питань`,
    progressLost: "Прогрес буде втрачено.",
    yesReset: "Так, скинути",
    cancelConfirm: "Скасувати",
    recordingStatus: "Запис…",
    processingRecording: "Обробка запису…",
    noSpeechDetected: "Нам не вдалося чітко почути. Спробуйте записати знову або надрукуйте відповідь.",
    noSoundLive: "Ми не чуємо жодного звуку. Перевірте мікрофон або зупиніть запис і надрукуйте відповідь.",
    transcriptHint: "Торкніться тексту вище, щоб внести зміни, або натисніть «Продовжити».",
    preferNotToSay: "Не бажаю вказувати",
    mapNudge: "Вибір штату додає вашу подорож на Карту подорожей.",
    ageGateTitle: "Перш ніж поділитися",
    ageGateBody: "Щоб наша спільнота залишалася безпечною, підтвердіть, будь ласка, дату народження перед публікацією своєї історії.",
    ageGateMonth: "Місяць",
    ageGateDay: "День",
    ageGateYear: "Рік",
    ageGateConfirm: "Продовжуючи, ви підтверджуєте точність цієї інформації.",
    ageGateContinue: "Продовжити",
    ageGateSubmitting: "Перевірка…",
    ageGateError: "Будь ласка, виберіть коректну дату народження.",
    ageGateBlockedTitle: "Дякуємо, що повідомили нам",
    ageGateBlockedBody: "Щоб ділитися історією тут, вам має бути щонайменше 13 років. Сподіваємося, ви повернетеся, коли станете трохи старшими!",
  },
  el: {
    placeholder: "Μοιραστείτε την απάντησή σας… (Enter για αποστολή, Shift+Enter για νέα γραμμή)",
    placeholderRecording: "Ηχογράφηση… κάντε κλικ στο ⏹ για διακοπή",
    placeholderWaiting: "Αναμονή για απάντηση…",
    clickToTalk: "Κάντε κλικ να μιλήσετε",
    recordingLabel: "Ηχογράφηση…",
    clickToStop: "Κλικ για διακοπή",
    continueBtn: "Συνέχεια",
    replay: "Επανάληψη",
    stop: "Διακοπή",
    startOver: "Ξεκινήστε από την αρχή",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} ερωτήσεις`,
    progressLost: "Η πρόοδος θα χαθεί.",
    yesReset: "Ναι, επαναφορά",
    cancelConfirm: "Ακύρωση",
    recordingStatus: "Ηχογράφηση…",
    processingRecording: "Επεξεργασία ηχογράφησης…",
    noSpeechDetected: "Δεν μπορέσαμε να σας ακούσουμε καθαρά. Δοκιμάστε να ηχογραφήσετε ξανά ή πληκτρολογήστε την απάντησή σας.",
    noSoundLive: "Δεν ακούμε κανέναν ήχο. Ελέγξτε το μικρόφωνό σας ή σταματήστε και πληκτρολογήστε την απάντησή σας.",
    transcriptHint: "Πατήστε το κείμενο παραπάνω για να κάνετε αλλαγές, ή πατήστε Συνέχεια.",
    preferNotToSay: "Προτιμώ να μην απαντήσω",
    mapNudge: "Η επιλογή πολιτείας προσθέτει το ταξίδι σας στον Χάρτη Ταξιδιού.",
    ageGateTitle: "Πριν μοιραστείτε",
    ageGateBody: "Για να διατηρήσουμε την κοινότητά μας ασφαλή, επιβεβαιώστε την ημερομηνία γέννησής σας πριν μοιραστείτε την ιστορία σας.",
    ageGateMonth: "Μήνας",
    ageGateDay: "Ημέρα",
    ageGateYear: "Έτος",
    ageGateConfirm: "Συνεχίζοντας, επιβεβαιώνετε ότι αυτές οι πληροφορίες είναι ακριβείς.",
    ageGateContinue: "Συνέχεια",
    ageGateSubmitting: "Έλεγχος…",
    ageGateError: "Επιλέξτε μια έγκυρη ημερομηνία γέννησης.",
    ageGateBlockedTitle: "Σας ευχαριστούμε που μας ενημερώσατε",
    ageGateBlockedBody: "Πρέπει να είστε τουλάχιστον 13 ετών για να μοιραστείτε μια ιστορία εδώ. Ελπίζουμε να επιστρέψετε όταν είστε λίγο μεγαλύτεροι!",
  },
  vi: {
    placeholder: "Chia sẻ câu trả lời của bạn… (Enter để gửi, Shift+Enter để xuống dòng)",
    placeholderRecording: "Đang ghi âm… nhấn ⏹ để dừng",
    placeholderWaiting: "Đang chờ phản hồi…",
    clickToTalk: "Nhấn để nói",
    recordingLabel: "Đang ghi…",
    clickToStop: "Nhấn để dừng",
    continueBtn: "Tiếp tục",
    replay: "Phát lại",
    stop: "Dừng",
    startOver: "Bắt đầu lại",
    progressText: (n) => `${n}/${TOTAL_QUESTIONS} câu hỏi`,
    progressLost: "Tiến trình sẽ bị mất.",
    yesReset: "Có, đặt lại",
    cancelConfirm: "Hủy",
    recordingStatus: "Đang ghi…",
    processingRecording: "Đang xử lý ghi âm…",
    noSpeechDetected: "Chúng tôi không nghe rõ. Hãy thử ghi âm lại hoặc nhập câu trả lời của bạn.",
    noSoundLive: "Chúng tôi không nghe thấy âm thanh. Kiểm tra micrô của bạn, hoặc dừng lại và nhập câu trả lời.",
    transcriptHint: "Chạm vào văn bản ở trên để chỉnh sửa, hoặc nhấn Tiếp tục.",
    preferNotToSay: "Không muốn tiết lộ",
    mapNudge: "Chọn một bang sẽ thêm hành trình của bạn vào Bản đồ Hành trình.",
    ageGateTitle: "Trước khi chia sẻ",
    ageGateBody: "Để giúp cộng đồng của chúng tôi luôn an toàn, vui lòng xác nhận ngày sinh của bạn trước khi chia sẻ câu chuyện.",
    ageGateMonth: "Tháng",
    ageGateDay: "Ngày",
    ageGateYear: "Năm",
    ageGateConfirm: "Khi tiếp tục, bạn xác nhận thông tin này là chính xác.",
    ageGateContinue: "Tiếp tục",
    ageGateSubmitting: "Đang kiểm tra…",
    ageGateError: "Vui lòng chọn ngày sinh hợp lệ.",
    ageGateBlockedTitle: "Cảm ơn bạn đã cho chúng tôi biết",
    ageGateBlockedBody: "Bạn phải từ 13 tuổi trở lên để chia sẻ câu chuyện tại đây. Chúng tôi mong bạn quay lại chia sẻ khi lớn hơn một chút!",
  },
};

export function getUIStrings(lang: string): UIStrings {
  return UI_STRINGS[lang] ?? UI_STRINGS["en"];
}
